### ISSUE TITLE
Generation Fails When Referencing Inherited Properties

### ISSUE THREAD

**Issue by AinoraZ** [koenbeuk/EntityFrameworkCore.Projectables#10]
Seems that the source generator does not pick up inherited properties.
```csharp
public class ReproductionEntity : BaseEntity
{
    [Projectable]
    public int TotalChildren => Children.Count;
}
```

Will fail at build time with ```The name 'Children' does not exist in the current context```.
Attaching minimal reproduction project. [Minimal Reproduction.zip](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/files/7662780/Minimal.Reproduction.zip)

EF Core version: 6.0.0
Projectables version: 2.0.2

**Comment by koenbeuk** [comment]
Thanks for reporting this and a big thanks for including the repro!

It indeed seems as code generation issue, I will get on this in the coming days. In the meantime, you can use the following workaround:

```csharp
    public class WorkAroundEntity : BaseEntity
    {
        
    }

    public static class WorkAroundEntityExtensions
    {
        [Projectable]
        public static int TotalChildren(this WorkAroundEntity workAroundEntity)
            => workAroundEntity.Children.Count;
    }
```

**Comment by koenbeuk** [comment]
@AinoraZ 

Perhaps a simpler workaround:

```csharp
[Projectable]
public int TotalChildren => this.Children.Count;
```

By explicitly using `this`. The generator is aware of the actual receiver and will generate an acceptable expression

**Comment by AinoraZ** [comment]
> @AinoraZ
> 
> Perhaps a simpler workaround:
> 
> ```cs
> [Projectable]
> public int TotalChildren => this.Children.Count;
> ```
> 
> By explicitly using `this`. The generator is aware of the actual receiver and will generate an acceptable expression

Tried this as such in the minimal repro project:
```csharp
public class ReproductionEntity : BaseEntity
{
    [Projectable]
    public int TotalChildren => this.Children.Count;
}
```

Got error on build: ```Keyword 'this' is not valid in a static property, static method, or static field initializer```.

**Comment by koenbeuk** [comment]
@AinoraZ Apologies, I indeed have to conclude that the alternative suggested workaround also fails to compile
