### ISSUE TITLE
NuGet packages named "preiew" instead of "preview"

### ISSUE THREAD

**Issue by rmunn** [koenbeuk/EntityFrameworkCore.Projectables#106]
There appears to be a typo in the build process: the version numbers listed at https://www.nuget.org/packages/EntityFrameworkCore.Projectables and https://www.nuget.org/packages/EntityFrameworkCore.Projectables.Abstractions are showing as "4.0.0-preiew.2" instead of "4.0.0-preview.2" (and same for 4.0.0-preview.1).

**Comment by ZvonimirMatic** [comment]
Created a PR to fix this.

https://github.com/koenbeuk/EntityFrameworkCore.Projectables/pull/108

@rmunn @koenbeuk
