### ISSUE TITLE
Auto-configure projectable properties as [NotMapped]

### ISSUE THREAD

**Issue by Bretttt** [koenbeuk/EntityFrameworkCore.Projectables#109]
All `IEnumerable<>` projectable properties have to be marked as
`[NotMapped]` or EF throws an error. Example:

```
[Projectable]
public IEnumerable<MyThings> MySpecialThings => MyThings.Where(t => t.IsSpecial);
```

EF appears to be trying to map all properties defined as `IEnumerable<>` or `ICollection<>` as navigation properties, even if they are get-only (which, needless to say, includes properties like the above). 

I could be convinced otherwise, but I would make the case that _all_ projectable properties will always be unmapped.

It would be nice to have this library iterate through the models as part of model building and call `.Ignore(theProjectableProperty)`

**Comment by ZvonimirMatic** [comment]
I agree that all projectable properties should be unmapped by default.

@koenbeuk What do you think? I think I could do this, if it's all right with you.
