### ISSUE TITLE
EF Core 9 compatibility:  Method 'PrecompileQuery' in type 'CustomQueryCompiler'  does not have an implementation.

### ISSUE THREAD

**Issue by kerimcharfi** [koenbeuk/EntityFrameworkCore.Projectables#122]
I'm facing this Exception when upgrading to EF Core 9

<pre>
Unhandled exception. System.TypeLoadException:   
   Method 'PrecompileQuery' in type 'EntityFrameworkCore.Projectables.Infrastructure.Internal.CustomQueryCompiler' from assembly 
  'EntityFrameworkCore.Projectables, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fc5550082a9c642c' 
   does not have an implementation.

at EntityFrameworkCore.Projectables.Infrastructure.Internal.ProjectionOptionsExtension.ApplyServices(IServiceCollection services)
at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
...
</pre>

Packages:
```    
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0"> 
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0-rc.2" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  <PrivateAssets>all</PrivateAssets>
</PackageReference>

<PackageReference Include="EntityFrameworkCore.Projectables" Version="3.0.4" />
```

**Comment by zotanmew** [comment]
See #110, this was fixed in `4.0.0-preview4`. It would be great to have a stable release, though.
