### ISSUE TITLE
Am I misunderstanding the usage?

### ISSUE THREAD

**Issue by ByZhouhang** [koenbeuk/EntityFrameworkCore.Projectables#22]
``` C#
public class User:
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }

     [Projectable] 
     public string FullName => LastName + " / " + FirstName;

    }

// want  wirte like this  
_userRepository.Where(t => t.FullName .Contains("CC")).First()    //Translation of member 'FullName' on entity type 'User' failed

_userRepository.Select(t => t.FullName).First()  //will cause  query for all fields  (not   LastName FirstName  two filed)
```

**Comment by koenbeuk** [comment]
You'll have to enable `Projectables` within your DbContext:

e.g. in case of DI:
```csharp
services.AddDbContext<ApplicationDbContext>(options => {
      options
          .UseSqlite(dbConnection)
          .UseProjectables() // Add this line
  })
```

I'll update the readme to reflect this information, thanks for bringing it up!

**Comment by ByZhouhang** [comment]
> You'll have to enable `Projectables` within your DbContext:
> 
> e.g. in case of DI:
> 
> ```cs
> services.AddDbContext<ApplicationDbContext>(options => {
>       options
>           .UseSqlite(dbConnection)
>           .UseProjectables() // Add this line
>   })
> ```

thanks，The reason for the difference is ？
1、[Projectable]  public string FullName => LastName + " / " + FirstName;
2、[Projectable]  public string FullName =>  => $"{LastName}  /  {FirstName}"
       _userRepository.Where(t => t.FullName .Contains("CC")).First()    // 2. will error  can  not  translate  string.formate

**Comment by koenbeuk** [comment]
@ByZhouhang 

EF Core does not support string interpolation (String.Format), this library does not change that fact, see: https://github.com/dotnet/efcore/issues/6532#issuecomment-840081767
