### ISSUE TITLE
Translation of Projectable property fails

### ISSUE THREAD

**Issue by beercsaba** [koenbeuk/EntityFrameworkCore.Projectables#24]
Hi,

What can be wrong in my code if translation of this simple projectable property fails (version is the latest 2.2.0, platform is .NET 6 with EF Core 6)?

query: `var q2 = context.Students.Where(x => x.IsPaid);`

Exception message when translate this query using `q2.ToQueryString()`:
_The LINQ expression 'DbSet<Student>()
    .Where(s => !(s.IsDeleted))
    .Where(s => s.IsPaid)' could not be translated. Additional information: Translation of member 'IsPaid' on entity type 'Student' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'._ 

Student class has some real properties and also this one in a partial class:
`        [Projectable]
        public bool IsPaid => PaymentMethod == 1;`

Configuration of dbcontext:
```    services.AddDbContextFactory<AppDbContext>((provider, options) => options
       .AddInterceptors(provider.GetRequiredService<FillAuditPropertiesInterceptor>())
       .UseSqlServer(configuration.GetConnectionString(nameof(AppDbContext)))
       .ConfigureWarnings(x => x.Ignore(SqlServerEventId.SavepointsDisabledBecauseOfMARS)) //
       .UseInternalServiceProvider(provider)
       .UseProjectables(o => o.CompatibilityMode(EntityFrameworkCore.Projectables.Infrastructure.CompatibilityMode.Full)), ServiceLifetime.Scoped); 
```

Content of generated file:
```
using AB.KELLO.TANK2.Features.Infrastructure.Database.Interfaces;
using EntityFrameworkCore.Projectables;
using AB.KELLO.TANK2.Features.Domain.Entities;

namespace EntityFrameworkCore.Projectables.Generated
#nullable disable
{
    public static class AB_KELLO_TANK2_Features_Domain_Entities_Student_IsPaid
    {
        public static System.Linq.Expressions.Expression<System.Func<global::AB.KELLO.TANK2.Features.Domain.Entities.Student, bool>> Expression()
        {
            return (global::AB.KELLO.TANK2.Features.Domain.Entities.Student @this) => 
                @this.PaymentMethod == 1;
        }
    }
}
```

Query filter is used, that causes this part of the query: ` .Where(s => !(s.IsDeleted))`

Context is prepared for using Projectables (UseProjectables() is called) , attribute is used on property... 

Do you have any idea what is wrong here?

**Comment by koenbeuk** [comment]
Thanks for reporting this!

I suspect you may be running into issues with configuring a custom `InternalServiceProvider`. This may override the effect of `UseProjectables`. 

Can you try and call `query.ExpandProjectables()` in your query? this will force the Projectable members to be replaced with their generated expression. This extension method is available in the namespace `EntityFrameworkCore.Projectables.Extensions`.

Looking forward to hearing if that worked.

**Comment by beercsaba** [comment]
Hi,

calling ExpandProjectables() in this way
`var q = context.Students.Where(x => x.SchoolId == schoolId && !x.IsPaid).ExpandProjectables();`

throws this exception:
```[ERR] Unable to resolve generated expression
System.InvalidOperationException: Unable to resolve generated expression
   at EntityFrameworkCore.Projectables.Services.ProjectionExpressionResolver.FindGeneratedExpression(MemberInfo projectableMemberInfo)
   at EntityFrameworkCore.Projectables.Services.ProjectableExpressionReplacer.VisitMember(MemberExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at EntityFrameworkCore.Projectables.Services.ProjectableExpressionReplacer.VisitMethodCall(MethodCallExpression node)
   at EntityFrameworkCore.Projectables.Extensions.ExpressionExtensions.ExpandProjectables(Expression expression)
   at EntityFrameworkCore.Projectables.Extensions.QueryableExtensions.ExpandProjectables[TModel](IQueryable`1 query)```

**Comment by koenbeuk** [comment]
It seems to fail on this [line](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/blob/5cd98f68d20dcf5710b52e9efa885415f0972ede/src/EntityFrameworkCore.Projectables/Services/ProjectionExpressionResolver.cs#L25): 
```csharp
  var expressionFactoryMethod = reflectedType.Assembly
      .GetTypes()
      .Where(x => x.FullName == generatedContainingTypeName)
      .SelectMany(x => x.GetMethods())
      .FirstOrDefault();
```

Where reflectedType should be `Student` and generatedContainingTypeName should be `AB_KELLO_TANK2_Features_Domain_Entities_Student_IsPaid`. Can you confirm if this is the case? Otherwise, can you share a repro of this issue?

Thanks!

**Comment by beercsaba** [comment]
Hi,

If we use the given values ("Student" and "AB_KELLO_TANK2_Features_Domain_Entities_Student_IsPaid") this query will fail always.

Full name of a type contains the name of the namespace also.

The namespace of the generated class is `EntityFrameworkCore.Projectables.Generated`  (from the generated file).

You may rewrite the Where part of the query llike this:
`.Where (x => x.Namespace == "EntityFrameworkCore.Projectables.Generated" && x.Name == generatedContainingTypeName )`

In this way the method named Expression() will be the result of the query.

Maybe it helps...

**Comment by koenbeuk** [comment]
Thanks for trying that query, 

> Full name of a type contains the name of the namespace also.

That is what gets composed into `generatedContainingTypeName`. E.g. A projectable like:
```csharp
namespace Test
  class User {
    [Projectable] public int Age => 1; 
  }
}
``` 

Will generate: `EntityFrameworkCore.Projectables.Generated.Test_User_Age` as the generatedContainingTypeName value.

The Exception contains a data property: `GeneratedContainingTypeName`. This should be the FullName of the type that its looking for, can you share the value here?

![image](https://user-images.githubusercontent.com/2912652/166290825-d0e59c8d-d704-41e2-8ac6-9a00e936d690.png)

**Comment by beercsaba** [comment]
Hi,

I don't know why, but calling ExpandProjectables() at the end of the query makes it compileable now.
So this works now:  
`var q = context.Students.Where(x => x.SchoolId == schoolId && !x.IsPaid).ExpandProjectables();`

Yesterday the same code threw exception with message 'Unable to resolve generated expression', and i don't know how it got better. :) 

While it is ugly to call ExpandProjectables(), the compilation works at least. :)
Tomorrow i will try to check it in more complex cases.

Anyway, it would be very useful to be able to get rid of ExpandProjectables() calls... Dou you think this is possible and could happen in the next 1-2 weeks?

Thank You for all Your work and attention!

**Comment by koenbeuk** [comment]
@beercsaba I am not able to give any guarantees on this matter however if we can find the root cause of this issue and a proper fix, then I'm happy to release a new version of this library within a short time window.

Given that it seems to work when manually calling `ExpandProjectables`, then I would suspect that the issue may be due to your InternalServiceProvider, can you try and run the query without ExpandProjectables and without configuring an InternalServiceProvider? If that works then I can dive into that particular scenario.

Thanks!

**Comment by beercsaba** [comment]
Hi,

i don't expect any guarantees of course! Just trying to make this useful and promising library better.. :)

Without using internal service provider (i commented out line `.UseInternalServiceProvider(provider)` in configuration of connection factory) and without calling .ExpandProjectables() at the end of the query
```
var students = context.Students
  .Where(x => x.SchoolId == schoolId && x.IsNormative && !x.IsPaid)
  .Select(x => new { x.SchoolClass.GradeYear.GradeNumber, x.IsNationality, x.IsSpecialEducated })
   //.ExpandProjectables()
   ;
```
this exception comes:
```
[ERR] The LINQ expression 'DbSet<Student>()
    .Where(s => !(s.IsDeleted))
    .Where(s => s.SchoolId == __schoolId_0 && s.IsNormative && !(s.PaymentMethod == PaymentMethod.ValueOfPaid))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
System.InvalidOperationException: The LINQ expression 'DbSet<Student>()
    .Where(s => !(s.IsDeleted))
    .Where(s => s.SchoolId == __schoolId_0 && s.IsNormative && !(s.PaymentMethod == PaymentMethod.ValueOfPaid))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()

```

IsPaid is the projectable property defined like this:
```
using EntityFrameworkCore.Projectables;

using EPaymentMethod = AB.KELLO.TANK2.Features.Domain.Enums.PaymentMethod;

namespace AB.KELLO.TANK2.Features.Domain.Entities
{
    public partial class Student
    {
        [Projectable]
        public bool IsPaid => PaymentMethod == EPaymentMethod.ValueOfPaid;
    }
}
```

Where EPaymentMethod is a SmartEnum:
```
   public class PaymentMethod : SmartEnum<PaymentMethod, int>
    {
        public static readonly int ValueOfPaid = 1;
        public static readonly int ValueOfFreeOfCharge = 2;
        ...
```

configuration of ConnectionFactory:
```
            services.AddDbContextFactory<AppDbContext>((provider, options) => options
                .AddInterceptors(provider.GetRequiredService<FillAuditPropertiesInterceptor>())
                .UseSqlServer(configuration.GetConnectionString(nameof(AppDbContext)))
                .UseProjectables()
                .ConfigureWarnings(x => x.Ignore(SqlServerEventId.SavepointsDisabledBecauseOfMARS))                                                                                                     
               //.UseInternalServiceProvider(provider)
                , ServiceLifetime.Scoped);
```

Thank You for spending Your time on this!

**Comment by koenbeuk** [comment]
@beercsaba 

I've finally spent some time checking this out. My findings: 

`UseInternalServiceProvider` will replace the service provider built by EF Core. In your example, AddInterceptors, UseSqlServer, UseProjectables and ConfigureWarnings have no effect as they are configuring the built-in service provider of EF Core, not the InternalServiceProvider that is eventually getting used.

Please make sure that `UseProjectables` is called on the ServiceCollection from which your internal service provider is constructed.

**Comment by koenbeuk** [comment]
@beercsaba 

This line: ` services.AddEntityFrameworkSqlServer()` seems to be using a EF feature that has thus been removed, see https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.entityframeworkservicecollectionextensions.addentityframework?view=efcore-2.2 

You should consider removing reliance on that method.

Regardless: `AddEntityFrameworkSqlServer` registers EF core services and the SqlServer provider with the root service collection. This collection is later used to build a `ServiceProvider` which is then used to set as the internal ServiceProvider for the DbContextFactory. 

In other words: this statement `.UseInternalServiceProvider(provider), ServiceLifetime.Scoped)` eliminates much of the calls that have been placed before it, including ` .UseSqlServer(configuration.GetConnectionString(nameof(AppDbContext)))` and `.UseProjectables()`, as the ServiceCollection where these are registered with is not related to the ServiceProvider that EF will be using to resolve this.

Given the use of `UseInternalServiceProvider`, I'm not sure what a direct solution is, some possible candidates:
`services.AddEntityFrameworkSqlServer(options => options.UseProjectables())` may work if that overload exists. Otherwise, this should work:

```
services.AddEntityFrameworkSqlServer();
new EntityFrameworkCore.Projectables.Infrastructure.Internal.ProjectionOptionsExtension().ApplyServices(services);
```

But really, consider not changing the `InternalServiceProvider` since that will likely break stuff and its unlikely that you'll actually need it.

**Comment by koenbeuk** [comment]
Going to close this as the issue has become stale, feel free to reopen if this is still an issue
