### ISSUE TITLE
Alternate member for projectable expression

### ISSUE THREAD

**Issue by bocca** [koenbeuk/EntityFrameworkCore.Projectables#25]
For compatibility or performance reasons, sometimes the EF Core expression cannot be equal to the CLR expression. Although you can always have two public members (one with [Projectable] and one without it), that forces the user to know which member to use depending of the context. It would be nice to have only one public member, and instruct the library where to find the proper EF Core expression. I propose something like this:
```
[Projectable(UseMember = nameof(FooEF))] public string Foo => [...];
private string FooEF => [...];
```
UseMember instructs to find a meber with exact same signature (arguments, return type), except for different name.

**Comment by koenbeuk** [comment]
I like this proposal, one concern though:

Are we going to instruct the source generator where it can find the member that can be translated into an expression (and if none are specified, use the current body)? Or should we have an override system in place where we can manually define the expression that this library uses?

```csharp
class User {
     ...
     [Projectable(UseMember = "FullNameExpression")]
     public string FullName => $"{FirstName} {LastName}"; // Assuming string interpolation is not available in EF

     Expression<Func<User, string>> FullNameExpression(User user) => user.FirstName + " " + user.LastName;
}
```

The expression approach allows the user to take full control in exactly what expression gets used at runtime. The library will take care of swapping out calls to FullName with its expression counterpart.

Looking forward to more input.
