### ISSUE TITLE
How to test the new UseMemberBody feature added in #28

### ISSUE THREAD

**Issue by ThomasBjallas** [koenbeuk/EntityFrameworkCore.Projectables#29]
Hi,

I am trying to migrate from LinqKit to this great project but I have one last expression that works find in LingKit but I can't get to work with Projectables.

That is when I use the Expandable attribute to specify a MethodName, like this:
```
    [Expandable(nameof(QueryableDBTitleExpressionICollection))]
    public static string GetTitleWithDBFallback(this ICollection<UniqueTranslation> query)
    {
        return QueryableDBTitleExpressionICollection().Compile()(query);
    }
```

I have noticed that in pullrequest #28  (UseMemberBody to use the body of another member) a similar features has been added for Projectable. I would like to test the new UseMemberBody feature but since that has not yet been released, I am not sure how to test it.

I have tried to compile the project myself and then reference my built assemblies, but that does not work since SourceGenerator is never run when I compile.

Will you release a new version with the UseMemberBody soon, or can you help me how to test the new version myself?

**Comment by koenbeuk** [comment]
I just released v2.3.0-beta.1 which includes #28, see: https://www.nuget.org/packages/EntityFrameworkCore.Projectables/2.3.0-beta.1

Let me know if you run into any issues
