### ISSUE TITLE
Null propagating operator causes solution to not compile

### ISSUE THREAD

**Issue by schneidenbach** [koenbeuk/EntityFrameworkCore.Projectables#30]
If you define a property like this:

```
[Projectable]
public string StorageAccountName => StorageAccount?.Name
```

The solution will fail to compile, complaining "An expression tree lambda may not contain a null propagating operator."

Based on the implementation of the project, I believe this is expected behavior. However, given the use cases for using Projectables in the first place - could we simply instruct the source generator to not write the ?.

**Comment by koenbeuk** [comment]
This is already a feature but you'll have to enable it manually:
```csharp
[Projectable(NullConditionalRewriteSupport = NullConditionalRewriteSupport.Ignore)]
public string StorageAccountName => StorageAccount?.Name
```
