### ISSUE TITLE
Could Not Be Translated

### ISSUE THREAD

**Issue by Luca7993** [koenbeuk/EntityFrameworkCore.Projectables#31]
Hi,
i have this extension method

[Projectable]
        public static bool Filter(this Order x, List<int> suppliers) => suppliers.Count > 0 ? suppliers.Contains(x.Order.SupplierId) : true;

where I want to filter my orders by suppliers. But if suppliers list is empty I do not want to filter.
suppliers is a list of int that is coming from an internet request (so it isn't related to sql)

this give me this error 
The LINQ expression 'DbSet() .Where(i0 => EF.Property(EntityShaperExpression: Prafo.Data.Models.OrderValueBufferExpression: ProjectionBindingExpression: EmptyProjectionMember IsNullable: False , "Id") != null && object.Equals( objA: (object)EF.Property(EntityShaperExpression: Prafo.Data.Models.Order ValueBufferExpression: ProjectionBindingExpression: EmptyProjectionMember IsNullable: False , "Id"), objB: (object)EF.Property(i0, "OrderId"))) .Join( inner: DbSet(), outerKeySelector: i0 => EF.Property(i0, "OrderId"), innerKeySelector: c => EF.Property(c, "Id"), resultSelector: (o, i) => new TransparentIdentifier( Outer = o, Inner = i )) .Where(i0 => __model_Filter_Suppliers_0.Count > 0 ? __model_Filter_Suppliers_0.Contains(i0.Inner.SupplierId) : True)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

the problem is if i use the property passed in the argument that doesn't belong to sql
for example if i use

[Projectable]
        public static bool Filter(this Order x, List<int> suppliers) => suppliers.Count > 0;
i have the same error

but if i use just
[Projectable]
        public static bool Filter(this Order x, List<int> suppliers) =>  suppliers.Contains(x.Order.SupplierId;
it will be ok

for the moment, I solve the problem using "ExpandProjectables" method.
is something that can be improved or I should always use ExpandProjectables in these case?

thanks

**Comment by koenbeuk** [comment]
Try and switch to full compatibility mode:

```csharp
optionsBuilder.UseProjectables(options => {
    options.CompatibilityMode(EntityFrameworkCore.Projectables.Infrastructure.CompatibilityMode.Full);
});
```

Alternatively: you can manually force expansion of your query like so:

```csharp
_db.Orders
  .Filter(suppliers)
  .ExpandProjectables() // Add this
  .ToList();
```

**Comment by Luca7993** [comment]
> for the moment, I solve the problem using "ExpandProjectables" method.
> is something that can be improved or I should always use ExpandProjectables in these case?

yes, I've written at the end of the posts that using ExpandProjectables solve the problem, but I would know if it's a "bug", or it's normal to use ExpandProjetables in this case

thank you
