### ISSUE TITLE
Build errors due to StyleCop.Analyzers - auto-generated

### ISSUE THREAD

**Issue by djbsee** [koenbeuk/EntityFrameworkCore.Projectables#32]
I'm using EntityFrameworkCore.Projectables along with StyleCop.Analyzers and its giving build errors for the generated files:

SA1028 - Code must not contain trailing whitespace
SA1210 - Using directives must be ordered alphabetically by the namespaces

I think the fix may be to add this to the top of the generated files so StyleCop ignores them:

`// <auto-generated/>`

**Comment by koenbeuk** [comment]
Seems like this should be a simple fix though I've never used StyleCop. Would you be willing to issue a PR for this? The needed modifications can be made [here](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/blob/master/src/EntityFrameworkCore.Projectables.Generator/ProjectionExpressionGenerator.cs#L132)

**Comment by djbsee** [comment]
I've created a PR here https://github.com/koenbeuk/EntityFrameworkCore.Projectables/pull/33. I hope this is ok - I've not really used GitHub before. Thanks.

**Comment by koenbeuk** [comment]
@djbsee Thanks! fix looks good but the unit tests are now broken as the source gen's output is different from what was expected. Can you update the unit tests as well? This project is using https://github.com/VerifyTests/Verify

**Comment by djbsee** [comment]
Sorry! I've updated the expected files in EntityFrameworkCore.Projectables.Generator.Tests.

**Comment by koenbeuk** [comment]
Cheers for updating the tests, finally, the comment is now not at the top of the file but rather below the using statements, is that an issue?

**Comment by djbsee** [comment]
I don't think so. With the changes I've made I no longer get any StyleCopAnalyzers errors. So I assume it's ok anywhere in the top of the file.

**Comment by koenbeuk** [comment]
Merged, Thanks for your contribution!

**Comment by djbsee** [comment]
Grand! Thank you

**Comment by djbsee** [comment]
> Cheers for updating the tests, finally, the comment is now not at the top of the file but rather below the using statements, is that an issue?

Having updated to your latest beta I'm getting errors again. So I think you were right about this - auto-generated needs to be at the top. I've created a new PR - https://github.com/koenbeuk/EntityFrameworkCore.Projectables/pull/37

**Comment by koenbeuk** [comment]
Merged, this will be included in the next beta
