### ISSUE TITLE
"Unable to resolve generated expression" - default values for arguments not supported

### ISSUE THREAD

**Issue by bzbetty** [koenbeuk/EntityFrameworkCore.Projectables#34]
Not sure if I've missed a step somewhere, Getting the error "Unable to resolve generated expression " and when I view the outputted source in ILSpy it doesn't have the expression on the type at all.

I've tried instance method, static method and extension method.  Come to the conclusion that the source generator might not be running.

I do notice i don't have a reference to EntityFrameworkCore.Projectables.Generator nor doesn't there seem to be a nuget package for it.

Am i missing somethign?

**Comment by bzbetty** [comment]
Actually if I change the expression bodied member back to a function I get the error "EFP0001	Method or property '' should expose an expression body definition"

Which means the source generator does run, so must be something else that's happening

**Comment by bzbetty** [comment]
Ok looks like it was failing to generate due to a default value on the method.

**Comment by koenbeuk** [comment]
Reopening this as default values should be either supported or the error message should be descriptive
