### ISSUE TITLE
Create a generic projectable library

### ISSUE THREAD

**Issue by koenbeuk** [koenbeuk/EntityFrameworkCore.Projectables#4]
The current library is tied to EFCore (by name convention only). It would be relatively trivial to spawn of a new project that encapsulates the Projectable attribute, code generation and the ExpandProjectables() extension methods so that non EF projects can also take advantage of projectables.

**Comment by andrewboudreau** [comment]
Would something like this make it so that I don't have to install all the EF dependencies into my domain project in order to use projectables?  I'd love to see that.

**Comment by andrewboudreau** [comment]
What namespace are you thinking?

**Comment by koenbeuk** [comment]
Given that this library is called EntityFrameworkCore.Projectables and we're trying to release a library that targets Linq providers in general, I suppose `Linq.Projectables` would be a fitting name.

**Comment by koenbeuk** [comment]
Closing this as its currently out of scope given the state of the project.
