### ISSUE TITLE
[Question] Use projectables inside Where predicates

### ISSUE THREAD

**Issue by PhenX** [koenbeuk/EntityFrameworkCore.Projectables#40]
This is more a question than an issue, and I know this is not in adequation with the project's name (and goal), but I think the principle of this library could also be useful in Where queries.

What do you think ?

**Comment by koenbeuk** [comment]
Can you clarify what you would like to see included? You can currently already filter on Projectables, e.g.

```csharp
query.Where(x => x.MyProjectableMethod() > 10) // Perfectly valid and will be expanded to the expression of that projectable.
```

Thanks!

**Comment by koenbeuk** [comment]
Do the changes in the readme as part of this [PR](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/pull/43) answer your question?

**Comment by PhenX** [comment]
Yes! :) thank you
