### ISSUE TITLE
Support inheritance, abstract classes, and virtual members

### ISSUE THREAD

**Issue by RKukharchuk** [koenbeuk/EntityFrameworkCore.Projectables#52]
Hi, thanks for this library.

I'm having an issue with using projectable in the base class that needs to get a projectable expression from its derived classes. 
The base class is an abstract class.
Derived classes are EF entities.
The base class has projectable property Status, which needs data from derived classes. Adding an abstract member right now fails with a LINQ translation error.
Base class member:
```
[Projectable] public Status Status => IsActive ? Status.Active : Status.Pending
public abstract bool IsActive { get; }
```
Derived class:
```
[Projectable] public override bool IsActive => EndDate > DateTimeOffset.Now; 
```

**Comment by koenbeuk** [comment]
Thanks for reporting this. This is indeed a scenario that is not yet covered. I will look into implementing this in the coming days.
