### ISSUE TITLE
Unnecessary null check

### ISSUE THREAD

**Issue by gokhanabatay** [koenbeuk/EntityFrameworkCore.Projectables#56]
Thank you for great library it saves my time, when we are struggling to migrate nhibernate to ef core 7. 
We are storing DateTime as YYYYMMDD formatted in database. 

Below projectable generates following sql and it includes unnessary coalesce function why "BirthTime" alread not nullable integer property.

CAST((a.birth_date::text || **COALESCE**(lpad(a.birth_time::text, 6, '0'), '')) AS bigint) >= @__ToLongDateTime_0

```c#
public class Author
{
    public DateTime BirthDate {get; set;}
    public int BirthTime {get; set;}

    [Projectable]
    public long BirthDateTime => (long)(object)(BirthDate + BirthTime.ToString().PadLeft(6, '0'));
}
```

Details when I try to implement custom function. https://github.com/dotnet/efcore/issues/25980#issuecomment-1351480742

**Comment by koenbeuk** [comment]
The generated SQL is produced by EF, this library does not impact the SQL that gets generated.
