### ISSUE TITLE
Extension method not found when NullConditionalRewriteSupport is configured

### ISSUE THREAD

**Issue by buraktamturk** [koenbeuk/EntityFrameworkCore.Projectables#65]
Hello, thanks for such an amazing library again.

The build fails with 

```
'vfile' does not contain a definition for 'ToVFile' and no accessible extension method 'ToVFile' accepting a first argument of type 'vfile' could be found (are you missing a using directive or an assembly reference?)"
```

when using null propagation. Example code:

```csharp
public static class ContentExtensions
{
    [Projectable]
    public static VFile ToVFile(this vfile a) => new VFile
    {
        id = a.id
        // ...
    };
    
    [Projectable] // works when ? not used, fails when ? is used (this is intentional behaviour)
    [Projectable(NullConditionalRewriteSupport = NullConditionalRewriteSupport.Ignore)] // fails with the above error when ? is used
    [Projectable(NullConditionalRewriteSupport = NullConditionalRewriteSupport.Rewrite)] // fails with the same error when ? is used
    public static Content ToContent(this content ms) => new Content
    {
        featured_image = ms.featured_image?.ToFile()
    };
}
```

My guess is that the source generator does not qualify the assembly and the class correctly when handling null conditions.

Thanks a lot!

**Comment by koenbeuk** [comment]
The build failure seems unrelated to what this library is doing. (Also note that the code sample is broken).

This works for me:

```csharp
public class VFileDTO
{
    public int id { get; set; }
}

public class VFile
{
    public int id { get; set; }
}

public class ContentDTO
{
    public VFileDTO? featured_image { get; set; }
}

public class Content
{
    public VFile? featured_image { get; set; }
}

public static class ContentExtensions
{
    [Projectable]
    public static VFile ToVFile(this VFileDTO a) => new VFile {
        id = a.id
        // ...
    };

    [Projectable(NullConditionalRewriteSupport = NullConditionalRewriteSupport.Ignore)] // fails with the above error when ? is used
    public static Content ToContent(this ContentDTO ms) => new Content {
        featured_image = ms.featured_image?.ToVFile()
    };
}
```

**Comment by buraktamturk** [comment]
Oh, perhaps the problem occurs when the models are in different projects. Like this:

<img width="1313" alt="Screenshot 2023-03-17 at 12 30 24 AM" src="https://user-images.githubusercontent.com/3593288/225767442-cd53ff01-7e80-4e20-b40c-51abfda3118f.png">

Commenting the other code fixes the build issue:

<img width="1313" alt="Screenshot 2023-03-17 at 12 31 26 AM" src="https://user-images.githubusercontent.com/3593288/225767585-fef9112a-dce9-4cc6-8b2a-d68daea01f68.png">

**Comment by buraktamturk** [comment]
Sample project: [Archive.zip](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/files/10996386/Archive.zip)

**Comment by koenbeuk** [comment]
Good catch, this got introduced with the release of V3, in particular by this PR: https://github.com/koenbeuk/EntityFrameworkCore.Projectables/pull/49

ExtensionMethods are not getting fully qualified if any of the parents within the hierarchy are of ConditionalAccessExpressions. 

I'll work on a fix in the coming days.
