### ISSUE TITLE
Source generator stopped generating

### ISSUE THREAD

**Issue by honzapatCZ** [koenbeuk/EntityFrameworkCore.Projectables#73]
Hello
After some time the generator stopped generating any output(the runtime cannot resolve the generated function and nothing is shown in obj/generated). But despite the usual errors of source generators I don't see any errors in the console.
What would be the proper place to start looking?

**Comment by honzapatCZ** [comment]
Aaaand found it.
Apparently just adding partial namespace already counts as Qualified.

**Comment by koenbeuk** [comment]
@honzapatCZ Sounds like the source generator crashed on your provided code, this is a bug in this library. Can you share the code that was causing the source generator to fail?

**Comment by honzapatCZ** [comment]
```cs
public class AddressData
{
        .....sth
    
        [Projectable]
        public bool IsEEA => Country != null && NejAccountingAPI.Models.CountryExtensions.IsEEA(Country.Value);
}
public static class Ext{

        [Projectable]
        public static bool IsEEA(this Country country) => country switch
        {
            Country.AT => true,
            Country.BE => true,
            Country.BG => true,
            Country.HR => true,
            Country.CY => true,
            Country.CZ => true,
            Country.DK => true,
            Country.EE => true,
            Country.FI => true,
            Country.FR => true,
            Country.DE => true,
            Country.GR => true,
            Country.HU => true,
            Country.IE => true,
            Country.IT => true,
            Country.LV => true,
            Country.LT => true,
            Country.LU => true,
            Country.MT => true,
            Country.NL => true,
            Country.PL => true,
            Country.PT => true,
            Country.RO => true,
            Country.SK => true,
            Country.SI => true,
            Country.ES => true,
            Country.SE => true,
            Country.GB => true,
            _ => false
        };
}
```
The NejAccountingAPI.Models.CountryExtensions.IsEEA itself had an error of using switch in it, but that was not shown as it errored in the AddressData.
In the end I removed both Projectables, so I wont be able to use them in queries, but it hopefully doesnt matter.

**Comment by honzapatCZ** [comment]
And I just found a new Source Generator error
InvalidOperationException - Expected at least one conditional expression on the stack
this time it's telling me even less xc.
Well let's get hunting.

**Comment by koenbeuk** [comment]
This seems like a regression, I'll look into it
