### ISSUE TITLE
Unable to cast object of type 'EntityFrameworkCore.Projectables.Infrastructure.Internal.CustomQueryCompiler' to type 'Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler' when using Z.EntityFramework.Extensions and DeleteFromQuery

### ISSUE THREAD

**Issue by P9avel** [koenbeuk/EntityFrameworkCore.Projectables#78]
Hi. I am calling DeleteFromQuery method  from Z.EntityFramework.Extensions and now i am using yoour nuget.  In result, i am get error Unable to cast object of type 'EntityFrameworkCore.Projectables.Infrastructure.Internal.CustomQueryCompiler' to type 'Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler'. Possible can you to inherited your CustomQueryCompiler from 'Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler?

**Comment by koenbeuk** [comment]
Yes that should be possible. Happy to accept a PR here. 

A workaround would be to use limited compatibility mode as that replaces the `IQueryTranslationPreprocessorFactory` registration instead.

**Comment by P9avel** [comment]
Hi, i am removed  Z.EntityFramework.Extensions and using  ExecuteUpdate from EF Core7.0 now

**Comment by koenbeuk** [comment]
Closing this as providing compatibility seems somewhat out of scope and there is a workaround available
